require "plugins.gitsigns"
require "plugins.indent-blankline"
require "plugins.nvim-tree"
require "plugins.autopairs"
require "plugins.comment"
require "plugins.alpha"
require "plugins.project"
require "plugins.mappings"
